import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'cerveza',
    name: 'Cerveza artesanal',
    emoji: '🍺',
    imageUrl: 'https://i.imgur.com/rIaCQC9.jpeg',
    discountTiers: [
        { quantity: 2, percentage: 10 },
        { quantity: 3, percentage: 15 },
        { quantity: 4, percentage: 20 },
    ],
    kits: [
      {
        id: 'kit-completo-cerveza',
        name: 'Kit completo',
        description: 'Barril, canilla y balde con hielo. ¡Incluye regalos!',
        imageUrl: 'https://imgur.com/MemdnDx.jpeg',
        hasExtraBarrelSelector: false,
        price: 12000,
        yieldInfo: 'Todo listo para servir. Ideal para 15-20 personas.',
      },
      {
        id: 'kit-extra-cerveza',
        name: 'Kit + barril de recambio',
        description: 'Llevate el kit base y sumá barriles de repuesto.',
        imageUrl: 'https://imgur.com/LfBOdL6.jpeg',
        hasExtraBarrelSelector: true,
        price: 12000,
        pricePerExtraBarrel: 7000,
        yieldInfo: 'Kit base + barriles extra (40 pintas c/u).',
      },
      {
        id: 'solo-barril-cerveza',
        name: 'Solo el barril (10L)',
        description: 'Un barril de 10L con nuestra mejor cerveza artesanal.',
        imageUrl: 'https://imgur.com/x9N2mLT.jpeg',
        hasExtraBarrelSelector: false,
        price: 8500,
        yieldInfo: 'Rinde aprox. 20 pintas.',
      },
    ],
  },
  {
    id: 'fernet',
    name: 'Fernet con coca',
    emoji: '🥃',
    imageUrl: 'https://i.imgur.com/LZqB5FT.jpeg',
    discountTiers: [
        { quantity: 2, percentage: 5 },
        { quantity: 3, percentage: 10 },
        { quantity: 4, percentage: 15 },
    ],
    kits: [
      {
        id: 'kit-completo-fernet',
        name: 'Kit completo',
        description: 'Barril, canilla y balde con hielo. ¡Incluye regalos!',
        imageUrl: 'https://imgur.com/MemdnDx.jpeg',
        hasExtraBarrelSelector: false,
        price: 13000,
        yieldInfo: 'Todo listo para servir. Ideal para 20-25 personas.',
      },
      {
        id: 'kit-extra-fernet',
        name: 'Kit + barril de recambio',
        description: 'Llevate el kit base y sumá barriles de repuesto.',
        imageUrl: 'https://imgur.com/LfBOdL6.jpeg',
        hasExtraBarrelSelector: true,
        price: 13000,
        pricePerExtraBarrel: 7500,
        yieldInfo: 'Kit base + barriles extra (50 vasos c/u).',
      },
      {
        id: 'solo-barril-fernet',
        name: 'Solo el barril (10L)',
        description: 'Un barril de 10L del clásico Branca con Coca, listo para servir.',
        imageUrl: 'https://imgur.com/x9N2mLT.jpeg',
        hasExtraBarrelSelector: false,
        price: 9000,
        yieldInfo: 'Rinde aprox. 25 vasos.',
      },
    ],
  },
  {
    id: 'gin-tonic',
    name: 'Gin tonic',
    emoji: '🍸',
    imageUrl: 'https://i.imgur.com/oCl0lDc.jpeg',
    discountTiers: [
        { quantity: 2, percentage: 10 },
        { quantity: 3, percentage: 15 },
        { quantity: 4, percentage: 20 },
    ],
    kits: [
       {
        id: 'kit-completo-gin',
        name: 'Kit completo',
        description: 'Barril, canilla y balde con hielo. ¡Incluye regalos!',
        imageUrl: 'https://imgur.com/MemdnDx.jpeg',
        hasExtraBarrelSelector: false,
        price: 15000,
        yieldInfo: 'Todo listo para servir. Ideal para 20-25 personas.',
      },
      {
        id: 'kit-extra-gin',
        name: 'Kit + barril de recambio',
        description: 'Llevate el kit base y sumá barriles de repuesto.',
        imageUrl: 'https://imgur.com/LfBOdL6.jpeg',
        hasExtraBarrelSelector: true,
        price: 15000,
        pricePerExtraBarrel: 9000,
        yieldInfo: 'Kit base + barriles extra (45 copas c/u).',
      },
      {
        id: 'solo-barril-gin',
        name: 'Solo el barril (10L)',
        description: 'Un barril de 10L de gin tonic Navegante, fresco y equilibrado.',
        imageUrl: 'https://imgur.com/x9N2mLT.jpeg',
        hasExtraBarrelSelector: false,
        price: 11000,
        yieldInfo: 'Rinde aprox. 22 copas.',
      },
    ],
  },
];